version: "3.9"

services:
  php:
    build: ./php
    volumes:
      - "${APP_DIR}:/var/www/html"
      - "./supervisor:/etc/supervisor"
      - "./cron.d:/etc/cron.d"
      - "./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "${NGINX_CONF_DIR}/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - mysql
    networks:
      - database
      - nginx-proxy-network
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}


  mysql:
    image: mariadb:10.7.1
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - database

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    expose:
#      - "80"
#    environment:
#      PMA_HOST: mysql
#    depends_on:
#      - mysql
#    networks:
#      - database

  redis:
    image: redis:5.0.4
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD="${REDIS_PASSWORD}"
    networks:
      - database

networks:
  database:
  server:
  nginx-proxy-network:
    external:
        name: reverseproxy_default
